// No live requests, email, credentials, or database writes.
import { test, beforeEach, after } from 'node:test';
import assert from 'node:assert/strict';
import handler from '../api/sim-request.js';
const originalFetch=global.fetch,env={...process.env};let primaryOk,fallbackOk,emailOk,calls;
beforeEach(()=>{primaryOk=true;fallbackOk=true;emailOk=true;calls=[];process.env.SUPABASE_URL='https://unit-test.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='unit-test';process.env.RESEND_API_KEY='unit-test';process.env.CELLZTECH_NOTIFY_EMAIL='store@example.com';process.env.CELLZTECH_FROM_EMAIL='CellzTech <offers@example.com>';delete process.env.SUPABASE_SIM_REQUESTS_TABLE;delete process.env.SUPABASE_REPAIR_REQUESTS_TABLE;global.fetch=async(url,init)=>{const u=new URL(url);calls.push({url,body:JSON.parse(init.body)});const ok=u.hostname==='api.resend.com'?emailOk:u.pathname.endsWith('/ultra_sim_requests')?primaryOk:fallbackOk;assert(['api.resend.com','unit-test.invalid'].includes(u.hostname));return new Response(JSON.stringify(ok?(u.hostname==='api.resend.com'?{id:'mail-test'}:[{id:'request-test'}]):{message:'simulated-provider-failure'}),{status:ok?200:503});};});
after(()=>{global.fetch=originalFetch;for(const k of Object.keys(process.env))if(!(k in env))delete process.env[k];Object.assign(process.env,env);});
async function invoke(body={},method='POST'){const req={method,body:{requestType:'pickup',name:'Unit Test',phone:'3125550100',email:'test@example.com',planInterest:'Ultra 8GB holiday',selectedDuration:'12 months',selectedBilled:'$102',simQuantity:'1',...body}};const res={statusCode:200,body:null,setHeader(){},status(n){this.statusCode=n;return this;},json(o){this.body=o;return this;}};await handler(req,res);return res;}
test('records the complete October request and sends shop notification',async()=>{const r=await invoke();assert.equal(r.statusCode,200);assert.equal(r.body.saved,true);assert.equal(calls[0].body.raw_payload.selectedBilled,'$102');assert.equal(calls[0].body.customer_email,'test@example.com');});
test('database backup failure with successful fallback still reports saved',async()=>{primaryOk=false;const r=await invoke();assert.equal(r.body.saved,true);assert(calls.some(x=>x.url.endsWith('website_repair_requests')));});
test('email failure does not discard a saved request',async()=>{emailOk=false;const r=await invoke();assert.equal(r.statusCode,200);assert.equal(r.body.saved,true);assert.equal(r.body.notified,false);});
test('all destinations failing MUST return 503, never false success',async()=>{primaryOk=false;fallbackOk=false;emailOk=false;const r=await invoke();assert.equal(r.statusCode,503);assert.equal(r.body.ok,false);assert(!JSON.stringify(r.body).includes('simulated-provider-failure'));});
test('all destinations missing MUST return 503',async()=>{delete process.env.SUPABASE_URL;delete process.env.RESEND_API_KEY;const r=await invoke();assert.equal(r.statusCode,503);assert.equal(calls.length,0);});
test('shop email accepted with database unavailable reports received, not saved',async()=>{primaryOk=false;fallbackOk=false;const r=await invoke();assert.equal(r.statusCode,200);assert.equal(r.body.saved,false);assert.equal(r.body.notified,true);});
test('shipping requires address before any external action',async()=>{const r=await invoke({requestType:'shipping'});assert.equal(r.statusCode,400);assert.equal(calls.length,0);});
test('invalid email rejected before external action',async()=>{const r=await invoke({email:'bad'});assert.equal(r.statusCode,400);assert.equal(calls.length,0);});
test('GET is rejected',async()=>{assert.equal((await invoke({},'GET')).statusCode,405);assert.equal(calls.length,0);});
test('family preserves quantity four and total one hundred',async()=>{await invoke({planInterest:'Family 4 for $100',simQuantity:'4',selectedBilled:'$100'});assert.equal(calls[0].body.raw_payload.simQuantity,'4');assert.equal(calls[0].body.raw_payload.selectedBilled,'$100');});
