import React, { useState } from 'react';
import { AutumnLeaf, OctoberDetails } from './OctoberSeason';
import { ArrowRight, BatteryCharging, CheckCircle2, ChevronDown, Globe2, MapPin, Phone, ShieldCheck, Smartphone, Users, Wifi, Wrench, Camera, Plug, MessageCircle, ShoppingBag } from 'lucide-react';
import { octoberCopy, type OctoberLanguage, type OctoberCopy } from './october-copy';
import { familyTotals, holidayPlans, monthly25Plans, money, offerHref, periodLabel, HOLIDAY_END, RENEWAL_END } from './october-offers';

const mapUrl = 'https://www.google.com/maps/search/?api=1&query=Cellz+Repairz+3412+N+Harlem+Ave+Chicago+IL+60634';
function track(name: string, lang: OctoberLanguage) {
  if (typeof window === 'undefined') return;
  void fetch('/api/track-visit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, keepalive: true, body: JSON.stringify({ path: `/event/${name}`, page: name, language: lang, referrer: window.location.origin + window.location.pathname }) }).catch(() => undefined);
}
function Cta({ href, children, secondary = false, event = 'october_offer_inquiry', lang }: { href: string; children: React.ReactNode; secondary?: boolean; event?: string; lang: OctoberLanguage }) {
  return <a className={`oct-button${secondary ? ' oct-button-secondary' : ''}`} href={href} onClick={() => track(event, lang)}>{children}<ArrowRight size={17} aria-hidden="true" /></a>;
}
function SectionHeading({ label, title, text, seasonal = false }: { label?: string; title: string; text?: string; seasonal?: boolean }) {
  return <div className="oct-section-heading">{label && <span className={`oct-eyebrow${seasonal ? ' oct-season-label' : ''}`}>{seasonal && <AutumnLeaf />}{label}</span>}<h2>{title}</h2>{text && <p>{text}</p>}</div>;
}
function Eligibility({ children, t }: { children: React.ReactNode; t: OctoberCopy }) {
  return <details className="oct-terms"><summary>{t.ui.terms}<ChevronDown size={18} aria-hidden="true" /></summary><div>{children}</div></details>;
}
function ContactBlock({ lang }: { lang: OctoberLanguage }) {
  const t = octoberCopy[lang];
  return <section className="oct-contact" aria-labelledby="oct-contact-title"><div className="oct-container oct-contact-grid"><div><span className="oct-eyebrow">CELLZ REPAIRZ / CELLZTECH</span><h2 id="oct-contact-title">{t.contact.title}</h2><p>{t.contact.intro}</p><div className="oct-actions"><Cta href="tel:7734137489" lang={lang} event="october_call_click">773-413-7489</Cta><Cta href={mapUrl} lang={lang} secondary event="october_directions_click">{t.ui.directions}</Cta></div></div><address><MapPin size={25} aria-hidden="true" /><strong>3412 N Harlem Ave, STE A</strong><span>Chicago, IL 60634</span><span>{t.contact.hours}</span><a href="/contact">{t.ui.details} <ArrowRight size={15} /></a></address></div></section>;
}
function Faq({ lang, home = false }: { lang: OctoberLanguage; home?: boolean }) {
  const t = octoberCopy[lang];
  const items = home ? [t.faq[5], t.faq[0], t.faq[2]] : t.faq;
  return <section className="oct-section oct-faq"><div className="oct-container oct-faq-grid"><SectionHeading label="FAQ" title={t.ui.faq} /><div>{items.map(x => <details key={x.q}><summary>{x.q}<ChevronDown size={18} aria-hidden="true" /></summary><p>{x.a}</p></details>)}</div></div></section>;
}
function Transfer({ lang }: { lang: OctoberLanguage }) {
  const t = octoberCopy[lang];
  return <section className="oct-section oct-transfer" id="switch"><div className="oct-container"><SectionHeading label={t.transfer.badge} title={t.transfer.title} text={t.transfer.intro} /><ol>{t.transfer.steps.map((x,i) => <li key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3></li>)}</ol><div className="oct-transfer-bottom"><p><ShieldCheck size={19} aria-hidden="true" />{t.transfer.warning}</p><Cta href={offerHref('switch')} lang={lang}>{t.transfer.cta}</Cta></div></div></section>;
}
export function OctoberHome({ lang }: { lang: OctoberLanguage }) {
  const t = octoberCopy[lang];
  const active = Date.now() < Date.parse(HOLIDAY_END);
  const repairIcons = [Smartphone, BatteryCharging, Plug, Smartphone, Camera, MessageCircle];
  const issues = ['Cracked screen', 'Battery replacement', 'Charging port issue', 'Back glass', 'Camera issue', 'Other / not sure'];
  return <main className="oct-page oct-seasonal" id="main-content">
    <section className="oct-home-hero"><div className="oct-container oct-home-grid"><div className="oct-home-copy"><span className="oct-location"><MapPin size={14} />3412 N Harlem Ave · Chicago</span><p className="oct-eyebrow">{t.home.eyebrow}</p><h1>{t.home.title}<span>{t.home.accent}</span></h1><p className="oct-lede">{t.home.intro}</p><div className="oct-actions"><Cta href="/book-repair" lang={lang} event="october_repair_booking_click">{t.ui.book}</Cta><Cta href="/ultra-mobile" lang={lang} secondary>{t.ui.compare}</Cta></div><a className="oct-call-inline" href="tel:7734137489" onClick={() => track('october_call_click',lang)}><Phone size={16} />773-413-7489</a></div><div className="oct-device-card"><OctoberDetails variant="device" /><span className="oct-device-label">{t.home.artLabel}</span><picture><source type="image/webp" srcSet="/october/iphone-480.webp 480w, /october/iphone-800.webp 800w, /iphone-pro-realistic.webp 1306w" sizes="(max-width: 700px) 85vw, 440px" /><img src="/iphone-pro-realistic.webp" alt="iPhone Pro" width="1306" height="1828" fetchPriority="high" /></picture><div className="oct-device-caption"><ShieldCheck size={18} /><span>{t.home.artNote}</span></div></div></div>
      {active && <div className="oct-container"><a className="oct-hero-offer" href="/ultra-mobile#holiday"><span><img src="/october/ultra-logo-white.png" alt="Ultra Mobile" width="120" height="69" /></span><div><small>{t.home.offerTag}</small><strong>{t.holiday.badge} <span>· {periodLabel(12,lang)}</span></strong></div><div className="oct-hero-price"><b>$8.50<small>{t.ui.perMonth}</small></b><span>{t.ui.equivalent} · $102 {t.ui.upfront}</span><small>{t.home.offerSmall} · {t.ui.tax}</small></div><ArrowRight className="oct-offer-arrow" size={22} aria-hidden="true" /></a></div>}
    </section>
    <div className="oct-trust"><div className="oct-container">{t.home.trust.map((x,i)=>{const Icon=[ShieldCheck,Wifi,Phone,MapPin][i];return <div key={x}><Icon size={19}/><span>{x}</span></div>;})}</div></div>
    <section className="oct-section" id="october-offers"><div className="oct-container"><SectionHeading seasonal label={t.ui.october} title={t.home.offersTitle} text={t.home.offersIntro}/>{active ? <div className="oct-summary-grid"><article className="oct-summary oct-summary-purple"><span className="oct-eyebrow">{t.holiday.badge}</span><h3>{t.brief.holiday}</h3><div className="oct-summary-number">50<span>%</span><small>{({ en:'OFF', pl:'taniej', es:'menos', uk:'знижки' })[lang]}</small></div><p>{t.brief.holidayBody}</p><small>{t.ui.newCustomer} · {t.ui.tax}</small><a href="/ultra-mobile#holiday">{t.ui.details}<ArrowRight size={18}/></a></article><article className="oct-summary"><span className="oct-eyebrow">{t.monthly.badge}</span><h3>{t.brief.monthly}</h3><div className="oct-summary-number">$29<small>{t.ui.perMonth}</small></div><p>{t.brief.monthlyBody}</p><small>{t.ui.newCustomer} · {t.ui.tax}</small><a href="/ultra-mobile#monthly">{t.ui.details}<ArrowRight size={18}/></a></article><article className="oct-summary"><span className="oct-eyebrow">{t.family.badge}</span><h3>{t.brief.family}</h3><div className="oct-summary-number">$100<small>{t.ui.perMonth}</small></div><p>{t.brief.familyBody}</p><small>{t.ui.tax}</small><a href="/ultra-mobile#family">{t.ui.details}<ArrowRight size={18}/></a></article></div>:<p className="oct-notice">{t.ui.expired}</p>}<p className="oct-fine-print">{t.ui.offerEnds} {t.ui.noPayment}</p></div></section>
    <section className="oct-section oct-repairs" id="repairs"><div className="oct-container"><div className="oct-heading-row"><SectionHeading label="IPHONE · SAMSUNG · IPAD · MOTOROLA · GOOGLE PIXEL" title={t.home.repairTitle} text={t.home.repairIntro}/><a className="oct-text-link" href="/repairs">{t.repairs.link}<ArrowRight size={18}/></a></div><div className="oct-repair-grid">{t.repairs.names.map((x,i)=>{const Icon=repairIcons[i];return <a href={`/book-repair?issue=${encodeURIComponent(issues[i])}&source=october-home`} key={x} onClick={()=>track('october_repair_booking_click',lang)}><Icon size={28} strokeWidth={1.5}/><h3>{x}</h3><p>{t.repairs.descriptions[i]}</p><ArrowRight size={18} aria-hidden="true"/></a>;})}</div><p className="oct-fine-print"><ShieldCheck size={17}/>{t.repairs.warranty}</p><ol className="oct-process">{t.repairs.process.map((x,i)=><li key={x}><b>{i+1}</b><span>{x}</span></li>)}</ol><p className="oct-fine-print">{t.repairs.note}</p></div></section>
    <section className="oct-section oct-shop"><div className="oct-container oct-shop-grid"><div><span className="oct-eyebrow">CELLZTECH CHICAGO</span><h2>{t.home.localTitle}</h2><p>{t.home.localText}</p><Cta href="/contact" lang={lang} secondary>{t.ui.directions}</Cta></div><div className="oct-shop-card"><ShoppingBag size={31} strokeWidth={1.5}/><h3>{t.home.shopTitle}</h3><p>{t.home.shopText}</p><div><a href="/phones">{t.home.phones}<ArrowRight size={16}/></a><a href="/accessories">{t.home.accessories}<ArrowRight size={16}/></a></div></div></div></section>
    <Faq lang={lang} home/><ContactBlock lang={lang}/><div className="oct-container oct-legal">{t.contact.independent}</div>
  </main>;
}


export function OctoberUltra({ lang }: { lang: OctoberLanguage }) {
  const t = octoberCopy[lang];
  const [selected, setSelected] = useState(0);
  const [period, setPeriod] = useState(0);
  const [lines, setLines] = useState(4);
  const plan = holidayPlans[selected];
  const monthly = monthly25Plans[period];
  const active = Date.now() < Date.parse(HOLIDAY_END);
  const renewalActive = Date.now() < Date.parse(RENEWAL_END);
  return <main className="oct-page oct-ultra-page oct-seasonal" id="main-content">
    <section className="oct-ultra-hero"><OctoberDetails variant="ultra" /><div className="oct-container oct-ultra-grid"><div><img className="oct-ultra-logo" src="/october/ultra-logo-white.png" width="140" height="80" alt="Ultra Mobile"/><span className="oct-eyebrow oct-season-label"><AutumnLeaf />{t.ui.october}</span><h1>{t.holiday.title}<span>{t.holiday.accent}</span></h1><p className="oct-lede">{t.holiday.intro}</p><div className="oct-actions"><Cta href="#holiday" lang={lang}>{t.ui.allPlans}</Cta><Cta href="tel:7734137489" lang={lang} secondary event="october_call_click">{t.ui.call}</Cta></div><p className="oct-ultra-hero-note">{t.ui.newCustomer} · {t.ui.offerEnds}</p></div><div className="oct-plan-preview"><div className="oct-plan-top"><span>{t.holiday.badge}</span><Wifi size={22}/></div><h2>{t.ui.choose}</h2><div className="oct-plan-chips" role="group" aria-label={t.ui.choose}>{holidayPlans.map((p,i)=><button key={p.id} type="button" className={selected===i?'is-active':''} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{p.name}</button>)}</div><div className="oct-preview-price" aria-live="polite"><strong>{money(plan.monthly)}<small>{t.ui.perMonth}</small></strong><span>{t.ui.equivalent}</span><p><b>{money(plan.total)}</b> {t.ui.upfront} · {periodLabel(12,lang)}</p></div><div className="oct-mini-renewal"><span>{t.ui.standard}</span><b>{money(plan.standard)}</b></div><p className="oct-fine-print">{t.ui.newCustomer}. {t.ui.tax} {t.ui.priceNote}</p>{active?<Cta href={offerHref('holiday',plan.id)} lang={lang}>{t.ui.ask}</Cta>:<p>{t.ui.expired}</p>}</div></div></section>
    <nav className="oct-subnav" aria-label={t.ui.compare}><div className="oct-container">{[['holiday',t.holiday.badge],['monthly','25GB'],['family',t.family.badge],['renewal',t.renewal.badge],['roaming','Go Roam'],['ultra-faq','FAQ']].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</div></nav>
    <section className="oct-section" id="holiday"><div className="oct-container"><SectionHeading label={t.ui.newCustomer} title={t.holiday.subtitle} text={t.holiday.description}/><div className="oct-price-table" role="region" aria-label={t.holiday.subtitle} tabIndex={0}><table><thead><tr><th scope="col">{t.ui.plan}</th><th scope="col">{t.ui.equivalent}</th><th scope="col">{t.ui.total}<small>{t.ui.upfront}</small></th><th scope="col">{t.ui.standard}</th><th scope="col"><span className="oct-sr-only">{t.ui.ask}</span></th></tr></thead><tbody>{holidayPlans.map(p=><tr key={p.id}><th scope="row">{p.name}</th><td><span className="oct-mobile-label">{t.ui.equivalent}</span><strong>{money(p.monthly)}</strong>{t.ui.perMonth}</td><td className="oct-table-total"><span className="oct-mobile-label">{t.ui.total}</span><b>{money(p.total)}</b><small>{t.ui.upfront}</small></td><td><span className="oct-mobile-label">{t.ui.standard}</span>{money(p.standard)}</td><td><a href={active?offerHref('holiday',p.id):'tel:7734137489'} aria-label={`${t.ui.ask}: ${p.name}`}>{t.ui.ask}<ArrowRight size={16}/></a></td></tr>)}</tbody></table></div><p className="oct-fine-print">{t.ui.tax} {t.holiday.after} {t.ui.offerEnds}</p><div className="oct-included"><h3>{t.ui.included}</h3><ul>{t.holiday.features.map(x=><li key={x}><CheckCircle2 size={18}/>{x}</li>)}</ul></div><Eligibility t={t}><p>{t.holiday.eligibility}</p><p>{t.holiday.network}</p><p>{t.ui.noPayment}</p></Eligibility></div></section>
    <section className="oct-section oct-monthly" id="monthly"><div className="oct-container oct-dual"><div><SectionHeading label={t.monthly.badge} title={t.monthly.title} text={t.monthly.intro}/><ul className="oct-checklist">{t.monthly.features.map(x=><li key={x}><CheckCircle2 size={18}/>{x}</li>)}</ul><p className="oct-note">{t.monthly.separate}</p></div><div className="oct-monthly-card"><h3>{t.monthly.duration}</h3><div className="oct-duration-grid" role="group" aria-label={t.monthly.duration}>{monthly25Plans.map((p,i)=><button key={p.duration} type="button" onClick={()=>setPeriod(i)} className={period===i?'is-active':''} aria-pressed={period===i}>{periodLabel(p.duration,lang)}</button>)}</div><div className="oct-monthly-price" aria-live="polite"><strong>{money(monthly.monthly)}<small>{t.ui.perMonth}</small></strong><p><b>{money(monthly.total)}</b> {t.ui.upfront} · {periodLabel(monthly.duration,lang)}</p></div><p>{t.monthly.help}</p>{active?<Cta href={offerHref('25gb',undefined,monthly.duration)} lang={lang}>{t.ui.ask}</Cta>:<p>{t.ui.expired}</p>}<p className="oct-fine-print">{t.ui.newCustomer}. {t.ui.tax} {t.ui.offerEnds}</p></div><div className="oct-dual-full"><Eligibility t={t}><p>{t.monthly.rule}</p><p>{t.monthly.auto}</p></Eligibility></div></div></section>
    <section className="oct-section" id="family"><div className="oct-container oct-dual"><div className="oct-family-visual"><div className="oct-family-visual-copy"><span>{t.family.badge}</span><strong>$100<small>{t.ui.perMonth}</small></strong><p>{t.family.totalLabel}</p></div><img src="/october/family-devices.webp" alt={t.family.features[0]} width="461" height="379" loading="lazy"/><small>{t.ui.priceNote}</small></div><div><SectionHeading label={t.family.badge} title={t.family.title} text={t.family.intro}/><div className="oct-family-controls"><label htmlFor="oct-lines">{t.family.lineCount}</label><select id="oct-lines" value={lines} onChange={e=>setLines(Number(e.target.value))}>{[1,2,3,4].map(n=><option key={n} value={n}>{n}</option>)}</select><div aria-live="polite"><strong>{money(familyTotals[lines-1])}<small>{t.ui.perMonth}</small></strong><span>{t.family.priceFor}</span></div></div><div className="oct-line-breakdown">{[49,24,12,15].slice(0,lines).map((n,i)=><div key={i}><span>{t.family.lineLabels[i]}</span><b>{money(n)}</b></div>)}</div><Cta href={offerHref('family')} lang={lang}>{t.ui.check}</Cta><p className="oct-fine-print">{t.family.terms}</p></div><div className="oct-dual-full"><Eligibility t={t}><p>{t.family.eligibility}</p></Eligibility></div></div></section>
    <section className="oct-section oct-renewal" id="renewal"><div className="oct-container"><SectionHeading label={t.renewal.badge} title={t.renewal.title} text={t.renewal.intro}/><div className="oct-renewal-prices">{holidayPlans.map(p=><div key={p.id}><span>{p.name}</span><strong>{money(p.renewal)}</strong><small>{periodLabel(12,lang)}</small></div>)}</div><p className="oct-fine-print">{t.renewal.total}. {t.ui.tax}</p><p className="oct-renewal-rule">{t.renewal.rule}</p><Cta href={renewalActive?offerHref('renewal'):'tel:7734137489'} lang={lang} secondary>{t.renewal.cta}</Cta></div></section>
    <section className="oct-section oct-roam" id="roaming"><div className="oct-container oct-dual"><div><SectionHeading label={t.roam.badge} title={t.roam.title} text={t.roam.body}/><p>{t.roam.note}</p><Cta href={offerHref('roaming')} lang={lang}>{t.roam.cta}</Cta><a className="oct-text-link" href="https://www.ultramobile.com/blog/how-to-use-your-phone-abroad-with-the-go-roam-world-pass/" target="_blank" rel="noopener noreferrer">{t.roam.detail}<ArrowRight size={16}/></a></div><div className="oct-roam-pass"><img className="oct-roam-mark" src="/october/ultra-logo-white.png" width="105" height="59" alt="Ultra Mobile" loading="lazy"/><Globe2 size={42} strokeWidth={1.2}/><h3>Go Roam<br/>World Pass</h3><p>{t.roam.services}</p><img className="oct-roam-map" src="/october/roam-globe.webp" alt="" aria-hidden="true" width="1250" height="358" loading="lazy"/></div></div></section>
    <Transfer lang={lang}/><div id="ultra-faq"><Faq lang={lang}/></div><ContactBlock lang={lang}/><div className="oct-container oct-legal">{t.contact.independent}</div>
  </main>;
}