export type OctoberLanguage = 'en' | 'pl' | 'es' | 'uk';

const en = {
  ui: { october: 'OCTOBER 2026 · CHICAGO', book: 'Request a repair', call: 'Call the store', compare: 'Explore Ultra offers', details: 'See offer details', ask: 'Ask about this plan', choose: 'Choose your data', perMonth: '/mo', equivalent: 'monthly equivalent', upfront: 'paid upfront', tax: 'Taxes & fees extra.', newCustomer: 'New customers only', allPlans: 'Compare all 5 plans', plan: 'Monthly data', total: 'First 12 months', standard: 'Standard annual renewal', months: 'months', month: 'month', selected: 'Selected', back: 'Back to plans', terms: 'Eligibility & important details', offerEnds: 'Activate by December 31, 2026.', expired: 'This offer has ended. Contact us for current plans.', check: 'Check eligibility', faq: 'A few good questions.', home: 'Home', directions: 'Get directions', learn: 'Learn more', included: 'Included with eligible plans', priceNote: 'Plan only. Phone sold separately.', noPayment: 'No payment collected online. We confirm eligibility and the final price before activation.' },
  home: { eyebrow: 'YOUR LOCAL PHONE & WIRELESS SHOP', title: 'Phone repair in Chicago.', accent: 'Better connected.', intro: 'A cracked screen. A tired battery. A phone bill that could be lower. CellzTech helps with iPhone, Samsung and tablet repairs, Ultra Mobile plans, and phones you can buy locally.', artLabel: 'A better plan for the phone you love.', artNote: 'Keep your compatible unlocked phone. Keep your number.', offerTag: 'OCTOBER ULTRA MOBILE OFFER', offerSmall: '8GB plan · first 12 months · new customers', repairTitle: 'The phone you rely on. The help you need.', repairIntro: 'Start with what is wrong. We will review your device, explain the repair options and confirm parts, price and timing before work begins.', localTitle: 'Real help. Right here on Harlem.', localText: 'Visit Cellz Repairz for repairs, number transfers, phone setup and everyday tech questions. One local store, with people to help you choose.', shopTitle: 'More ways to keep moving.', shopText: 'Explore used and unlocked phones, chargers, cases and screen protection. Ask us about current stock and setup help.', phones: 'Browse phones', accessories: 'Explore accessories', offersTitle: 'October savings. Clearly explained.', offersIntro: 'Three different ways to save. Compare what you pay today, how long it lasts, and who qualifies.', trust: ['Lifetime warranty on select repairs', 'Free Ultra activation help', 'Keep your number', 'Local in-store support'] },
  repairs: { names: ['Screen replacement', 'Battery replacement', 'Charging problems', 'Back glass repair', 'Camera & sound', 'Not sure what is wrong?'], descriptions: ['Cracks, lines or touch problems.', 'A battery that does not last.', 'Loose ports or a phone that will not charge.', 'Repair options for damaged rear glass.', 'Camera, speaker and microphone faults.', 'Start with a device assessment.'], warranty: 'Warranty coverage depends on the repair and part selected. Your receipt lists the exact coverage. Physical damage is not covered by a defect warranty.', link: 'Explore all repair services', process: ['Tell us your device and issue', 'We confirm options and timing', 'Drop off your device at the store'], note: 'A requested drop-off time is not a confirmed appointment until we contact you.' },
  brief: { holiday: 'A full year. Half the plan price.', holidayBody: '50% off eligible 12-month plans. From $102 upfront for 8GB per month.', monthly: '25GB. A price to keep.', monthlyBody: '$29 on the single-month plan. Lower monthly equivalents with prepaid multi-month options.', family: 'Four lines. One smaller bill.', familyBody: '4 Ultra Unlimited lines for $100 per month total. Eligible new fourth lines qualify.' },
  holiday: { badge: 'HOLIDAY OFFER · 50% OFF', title: 'A full year of Ultra.', accent: 'Half the plan price.', intro: 'Choose an eligible 12-month plan and pay once for your first year. We help you check your phone, keep your number and activate in store.', subtitle: 'Five plans. No price guesswork.', description: 'Each price below is for all 12 months, paid upfront. The smaller monthly figure is an equivalent—not a monthly payment.', after: 'After the introductory year, standard pricing applies.', eligibility: 'For new subscribers whose phone number and device have not been active with Ultra in the previous 90 days. Activate and fund the plan during the offer period. Excludes the promotional 25GB plan. Cannot be combined with other customer offers.', features: ['5G / 4G LTE data', 'Unlimited nationwide talk & global text', 'Unlimited calling to 90+ international destinations', 'Talk & text while in Mexico and Canada', 'Hotspot & Wi-Fi calling', 'On the T-Mobile network'], network: 'Unlimited plans: heavy data users above 35GB/month may notice slower speeds when the network is busy. Video streams in SD. Hotspot: up to 10GB on Unlimited and 25GB on Unlimited+.', original: 'Standard price', discounted: 'Holiday total', heroNote: 'Select a plan to see the exact upfront price.' },
  monthly: { badge: '25GB FOR LIFE', title: 'Prefer a plan you can keep?', intro: 'Lock in the promotional 25GB price for as long as you remain active on your eligible plan. Choose your plan duration at activation.', duration: 'Choose your payment period', help: 'More months prepaid means a lower monthly equivalent.', rule: 'New customers only; phone number and device must not have been active with Ultra in the previous 90 days. Promotional pricing depends on remaining on the eligible plan. Switching plans, disconnection or failing to renew can end the discount. Choose the duration you want at activation; the offer does not allow later switching between promo durations.', auto: 'The $29 single-month plan also offers a $3 Auto-Renew discount when enrolled and paid with Auto-Renew: $26 plus tax.', separate: 'This is a separate offer, not eligible for the 50% holiday discount.', features: ['25GB high-speed data each month', 'Unlimited nationwide talk & global text', 'Calling to 90+ destinations', 'Hotspot and Wi-Fi calling'] },
  family: { badge: 'ULTRA FAMILY PLAN', title: 'Bring the family. Keep the value.', intro: 'Four Ultra Unlimited lines for $100 per month total, with international features and local activation help.', totalLabel: 'total for 4 lines / month', lineLabels: ['First line', 'Second line', 'Third line', 'New fourth line'], eligibility: 'For new accounts and eligible existing customers adding a new fourth Add-A-Line by December 31, 2026. The promotional price continues while qualifying lines remain active on the eligible plan. Tablets can count toward the four-line offer.', features: ['4 Unlimited lines', 'Up to 10GB hotspot per line', 'International calling included', 'Eligible new fourth line required'], compare: 'Compare the family total', lineCount: 'Number of lines', priceFor: 'Total monthly plan price', terms: 'Taxes and fees extra. Unlimited data speeds may slow during congestion after 35GB/month; SD video.' },
  renewal: { badge: 'ALREADY WITH ULTRA?', title: 'A renewal offer for eligible 2025 holiday customers.', intro: 'Some customers who joined through the 2025 Ultra Holiday promotion can get 33% off an eligible 12-month renewal—equivalent to four months of the plan free.', rule: 'Eligibility is account-specific. Ultra notifies qualifying customers by text, email or app notification. Active status is required; customers on Auto-Renew are not eligible. Excludes 25GB and Add-A-Line plans. Available through January 31, 2027. We will check the renewal credit and final amount with you.', total: 'Eligible 12-month renewal', cta: 'Ask us to check your renewal' },
  roam: { services: "Calls. Texts. Data. Your number.", badge: 'GO ROAM WORLD PASS', title: 'Going abroad? Take your number with you.', body: 'Ask about Ultra’s Go Roam World Pass for calls, texts and data while travelling. Ultra advertises options for less than $1/day on any plan.', note: 'Availability, speed and coverage vary by destination. The pass is a separate purchase. Confirm destination coverage, price and allowances before travelling.', cta: 'Ask about your destination', detail: 'View Ultra roaming information' },
  transfer: { badge: 'SWITCHING, MADE SIMPLE', title: 'New plan. Same number.', intro: 'We will help check compatibility and guide your number transfer in store.', steps: ['Bring a compatible unlocked phone', 'Get your current account number', 'Get your carrier’s transfer PIN', 'Keep your existing line active'], warning: 'Do not cancel your old service before the number transfer is complete.', cta: 'Get help switching' },
  contact: { title: 'Let’s find the right next step.', intro: 'Repair your phone, compare a plan, or check what is in stock. Talk to CellzTech in Chicago.', hours: 'Mon–Fri 11 AM–7 PM · Sat 11 AM–3 PM · Sunday closed', address: '3412 N Harlem Ave, STE A · Chicago, IL 60634', independent: 'CellzTech is operated by Cellz Repairz LLC. Independent repair business; not an Apple-authorized service provider. Device shown for illustration; no phone is included with a wireless plan.' },
  faq: [
    { q: 'Is $8.50 a monthly payment?', a: 'No. The 8GB holiday offer costs $102 upfront for the first 12 months, equivalent to $8.50 per month. Taxes and fees are extra. Standard pricing applies at renewal.' },
    { q: 'Can existing Ultra customers get 50% off?', a: 'The 50% holiday offer is for new subscribers. The number and device must not have been active with Ultra in the previous 90 days. Eligible 2025 holiday customers have a separate renewal offer, which we can check for you.' },
    { q: 'Can I keep my phone and number?', a: 'Usually, yes. Bring a compatible unlocked phone, your current carrier account number and transfer PIN. Keep your existing service active until the transfer finishes.' },
    { q: 'Does 25GB for life mean I never pay again?', a: 'No. You still pay for your selected plan duration. The promotional rate continues while you remain eligible and active on that plan. Plan changes or disconnection can end the discount.' },
    { q: 'Can I combine these offers?', a: 'The holiday and 25GB promotions cannot be combined with other customer offers. Family and renewal offers have their own eligibility rules. We will confirm the right option before activation.' },
    { q: 'How do I arrange a phone repair?', a: 'Use Request a repair to select your device, issue and preferred drop-off time. We contact you to confirm price, parts and timing. Lifetime warranty is available on select repairs; exact coverage is listed on your receipt.' }
  ],
  seo: { homeTitle: 'Phone Repair Chicago & Ultra Mobile | CellzTech', homeDescription: 'iPhone and Samsung repair in Chicago. Compare October Ultra Mobile offers, buy unlocked phones and get local help at Cellz Repairz, 3412 N Harlem Ave.', ultraTitle: 'Ultra Mobile Chicago: October Offers | CellzTech', ultraDescription: 'Compare Ultra Mobile holiday plans from $102 upfront for 12 months, 25GB plans and 4 lines for $100. Local activation and number-transfer help in Chicago.' }
};

const pl: typeof en = {
  ui: { october: 'PAŹDZIERNIK 2026 · CHICAGO', book: 'Zgłoś naprawę', call: 'Zadzwoń do sklepu', compare: 'Sprawdź oferty Ultra', details: 'Zobacz szczegóły', ask: 'Zapytaj o ten plan', choose: 'Wybierz pakiet danych', perMonth: '/mies.', equivalent: 'równowartość miesięczna', upfront: 'płatne z góry', tax: 'Podatki i opłaty dodatkowo.', newCustomer: 'Tylko dla nowych klientów', allPlans: 'Porównaj 5 planów', plan: 'Dane miesięcznie', total: 'Pierwsze 12 miesięcy', standard: 'Standardowe odnowienie roczne', months: 'miesięcy', month: 'miesiąc', selected: 'Wybrano', back: 'Powrót do planów', terms: 'Warunki i ważne informacje', offerEnds: 'Aktywuj do 31 grudnia 2026 r.', expired: 'Ta oferta już się zakończyła. Zapytaj o aktualne plany.', check: 'Sprawdź kwalifikację', faq: 'Warto wiedzieć.', home: 'Start', directions: 'Wyznacz trasę', learn: 'Dowiedz się więcej', included: 'W kwalifikujących się planach', priceNote: 'Cena dotyczy planu. Telefon sprzedawany osobno.', noPayment: 'Nie pobieramy płatności online. Przed aktywacją potwierdzamy warunki i ostateczną cenę.' },
  home: { eyebrow: 'TWÓJ LOKALNY SERWIS I SKLEP Z TELEFONAMI', title: 'Naprawa telefonów w Chicago.', accent: 'Lepiej połączeni.', intro: 'Pęknięty ekran, słaba bateria albo zbyt wysoki rachunek? CellzTech pomaga w naprawach iPhone, Samsung i tabletów, wyborze Ultra Mobile oraz zakupie telefonu na miejscu.', artLabel: 'Lepszy plan dla Twojego telefonu.', artNote: 'Zachowaj zgodny, odblokowany telefon i swój numer.', offerTag: 'PAŹDZIERNIKOWA OFERTA ULTRA MOBILE', offerSmall: 'Plan 8GB · pierwsze 12 miesięcy · nowi klienci', repairTitle: 'Telefon, na którym polegasz. Pomoc, której potrzebujesz.', repairIntro: 'Powiedz, co nie działa. Sprawdzimy urządzenie, wyjaśnimy opcje i potwierdzimy części, cenę oraz termin przed rozpoczęciem naprawy.', localTitle: 'Prawdziwa pomoc. Tutaj, przy Harlem.', localText: 'Odwiedź Cellz Repairz, aby naprawić telefon, przenieść numer, skonfigurować urządzenie lub zapytać o technologię. Wszystko w jednym lokalnym sklepie.', shopTitle: 'Więcej dla Twojego telefonu.', shopText: 'Sprawdź telefony używane i odblokowane, ładowarki, etui oraz ochronę ekranu. Zapytaj o aktualny stan i pomoc z konfiguracją.', phones: 'Zobacz telefony', accessories: 'Zobacz akcesoria', offersTitle: 'Październikowe oszczędności. Jasne zasady.', offersIntro: 'Trzy różne sposoby na oszczędzanie. Porównaj płatność z góry, czas trwania i warunki.', trust: ['Dożywotnia gwarancja na wybrane naprawy', 'Bezpłatna pomoc z aktywacją Ultra', 'Zachowaj swój numer', 'Lokalna pomoc w sklepie'] },
  repairs: { names: ['Wymiana ekranu', 'Wymiana baterii', 'Problemy z ładowaniem', 'Naprawa tylnego szkła', 'Aparat i dźwięk', 'Nie wiesz, co się zepsuło?'], descriptions: ['Pęknięcia, linie lub problemy z dotykiem.', 'Bateria, która szybko się rozładowuje.', 'Luźne gniazdo lub brak ładowania.', 'Opcje naprawy uszkodzonego tylnego szkła.', 'Usterki aparatu, głośnika i mikrofonu.', 'Zacznij od sprawdzenia urządzenia.'], warranty: 'Gwarancja zależy od naprawy i wybranej części. Dokładne warunki znajdują się na paragonie. Gwarancja na wady nie obejmuje uszkodzeń mechanicznych.', link: 'Zobacz wszystkie naprawy', process: ['Podaj model i opisz problem', 'Potwierdzimy opcje i termin', 'Przynieś urządzenie do sklepu'], note: 'Wybrana godzina przyjęcia jest prośbą — termin potwierdzimy w kontakcie z Tobą.' },
  brief: { holiday: 'Cały rok. Połowa ceny planu.', holidayBody: '50% taniej na wybrane plany roczne. Od $102 z góry za 8GB miesięcznie.', monthly: '25GB. Cena na dłużej.', monthlyBody: '$29 za plan jednomiesięczny. Niższa równowartość miesięczna przy opłaceniu kilku miesięcy z góry.', family: 'Cztery linie. Mniejszy rachunek.', familyBody: '4 linie Ultra Unlimited za łącznie $100 miesięcznie. Wymagana kwalifikująca się nowa czwarta linia.' },
  holiday: { badge: 'OFERTA ŚWIĄTECZNA · 50% TANIEJ', title: 'Cały rok z Ultra.', accent: 'Za połowę ceny planu.', intro: 'Wybierz kwalifikujący się plan roczny i opłać pierwszy rok jednorazowo. Pomożemy sprawdzić telefon, zachować numer i aktywować usługę w sklepie.', subtitle: 'Pięć planów. Wszystkie ceny jasno.', description: 'Każda kwota poniżej obejmuje 12 miesięcy płatnych z góry. Mniejsza kwota to równowartość miesięczna, a nie płatność co miesiąc.', after: 'Po pierwszym roku obowiązuje standardowa cena odnowienia.', eligibility: 'Dla nowych klientów, których numer i urządzenie nie były aktywne w Ultra przez poprzednie 90 dni. Plan trzeba aktywować i opłacić w okresie promocji. Promocyjny plan 25GB jest wyłączony. Oferty nie można łączyć z innymi promocjami dla klientów.', features: ['Dane 5G / 4G LTE', 'Nielimitowane rozmowy krajowe i globalne SMS-y', 'Nielimitowane rozmowy do ponad 90 kierunków', 'Rozmowy i SMS-y podczas pobytu w Meksyku i Kanadzie', 'Hotspot i rozmowy przez Wi-Fi', 'W sieci T-Mobile'], network: 'Plany Unlimited: po przekroczeniu 35GB/mies. prędkość może spadać w okresach przeciążenia sieci. Wideo w SD. Hotspot: do 10GB w Unlimited i 25GB w Unlimited+.', original: 'Cena standardowa', discounted: 'Suma w promocji', heroNote: 'Wybierz plan, aby zobaczyć pełną płatność z góry.' },
  monthly: { badge: '25GB ZE STAŁĄ CENĄ', title: 'Wolisz plan z ceną na dłużej?', intro: 'Zachowaj promocyjną cenę 25GB, dopóki pozostajesz aktywnym użytkownikiem kwalifikującego się planu. Wybierz okres przy aktywacji.', duration: 'Wybierz okres płatności', help: 'Więcej miesięcy opłaconych z góry oznacza niższą równowartość miesięczną.', rule: 'Tylko nowi klienci; numer i urządzenie nie mogą być aktywne w Ultra przez poprzednie 90 dni. Cena promocyjna zależy od utrzymania kwalifikującego się planu. Zmiana planu, odłączenie lub brak odnowienia mogą zakończyć rabat. Wybierz okres przy aktywacji — późniejsza zmiana okresu promocyjnego nie jest dostępna.', auto: 'Plan jednomiesięczny za $29 oferuje też $3 rabatu po zapisaniu się i opłacaniu przez Auto-Renew: $26 plus podatek.', separate: 'To osobna oferta, bez dodatkowego rabatu 50%.', features: ['25GB szybkich danych co miesiąc', 'Nielimitowane rozmowy krajowe i globalne SMS-y', 'Rozmowy do ponad 90 kierunków', 'Hotspot i rozmowy przez Wi-Fi'] },
  family: { badge: 'PLAN RODZINNY ULTRA', title: 'Połącz rodzinę. Zachowaj oszczędności.', intro: 'Cztery linie Ultra Unlimited za łącznie $100 miesięcznie, z funkcjami międzynarodowymi i lokalną pomocą przy aktywacji.', totalLabel: 'łącznie za 4 linie / miesiąc', lineLabels: ['Pierwsza linia', 'Druga linia', 'Trzecia linia', 'Nowa czwarta linia'], eligibility: 'Dla nowych kont i kwalifikujących się obecnych klientów dodających nową czwartą linię Add-A-Line do 31 grudnia 2026 r. Cena trwa, dopóki wymagane linie są aktywne na kwalifikującym się planie. Tablety mogą wchodzić w skład czterech linii.', features: ['4 linie Unlimited', 'Do 10GB hotspotu na linię', 'Rozmowy międzynarodowe w cenie', 'Wymagana nowa czwarta linia'], compare: 'Porównaj łączny koszt rodzinny', lineCount: 'Liczba linii', priceFor: 'Łączna miesięczna cena planu', terms: 'Podatki i opłaty dodatkowo. Po 35GB/mies. dane mogą zwalniać przy przeciążeniu sieci; wideo SD.' },
  renewal: { badge: 'KORZYSTASZ JUŻ Z ULTRA?', title: 'Odnowienie dla uprawnionych klientów promocji świątecznej 2025.', intro: 'Wybrani klienci, którzy dołączyli w promocji Ultra Holiday 2025, mogą otrzymać 33% rabatu na kwalifikujące się odnowienie roczne — równowartość czterech miesięcy gratis.', rule: 'Uprawnienia zależą od konta. Ultra powiadamia SMS-em, e-mailem lub w aplikacji. Konto musi być aktywne; klienci korzystający z Auto-Renew nie kwalifikują się. Wyłączone są plany 25GB i Add-A-Line. Oferta do 31 stycznia 2027 r. Wspólnie sprawdzimy kredyt na odnowienie i ostateczną kwotę.', total: 'Kwalifikujące się odnowienie na 12 miesięcy', cta: 'Zapytaj o swoje odnowienie' },
  roam: { services: "Rozmowy. SMS-y. Dane. Twój numer.", badge: 'GO ROAM WORLD PASS', title: 'Wyjeżdżasz? Zabierz swój numer.', body: 'Zapytaj o Go Roam World Pass do rozmów, SMS-ów i danych za granicą. Ultra reklamuje opcje za mniej niż $1 dziennie na dowolnym planie.', note: 'Dostępność, prędkość i zasięg zależą od kraju. Pakiet jest kupowany osobno. Przed podróżą potwierdź obsługiwany kraj, cenę i limity.', cta: 'Zapytaj o kraj podróży', detail: 'Sprawdź roaming Ultra' },
  transfer: { badge: 'PROSTE PRZENIESIENIE NUMERU', title: 'Nowy plan. Ten sam numer.', intro: 'W sklepie sprawdzimy zgodność telefonu i pomożemy w przeniesieniu numeru.', steps: ['Przynieś zgodny, odblokowany telefon', 'Przygotuj numer konta u operatora', 'Uzyskaj PIN do przeniesienia numeru', 'Zachowaj aktywną obecną usługę'], warning: 'Nie anuluj starej usługi przed zakończeniem przeniesienia numeru.', cta: 'Uzyskaj pomoc z przeniesieniem' },
  contact: { title: 'Znajdźmy najlepszy kolejny krok.', intro: 'Napraw telefon, porównaj plany lub sprawdź dostępne urządzenia. Porozmawiaj z CellzTech w Chicago.', hours: 'Pon.–pt. 11:00–19:00 · Sob. 11:00–15:00 · Niedziela nieczynne', address: '3412 N Harlem Ave, STE A · Chicago, IL 60634', independent: 'CellzTech prowadzi Cellz Repairz LLC. Niezależny serwis; nie jest autoryzowanym serwisem Apple. Telefon na ilustracji nie jest dołączony do planu.' },
  faq: [
    { q: 'Czy $8.50 to płatność miesięczna?', a: 'Nie. Świąteczny plan 8GB kosztuje $102 z góry za pierwsze 12 miesięcy, czyli równowartość $8.50 miesięcznie. Podatki i opłaty są dodatkowe. Przy odnowieniu obowiązuje cena standardowa.' },
    { q: 'Czy obecni klienci Ultra mogą otrzymać 50% rabatu?', a: 'Oferta 50% jest dla nowych klientów. Numer i urządzenie nie mogą być aktywne w Ultra przez poprzednie 90 dni. Uprawnieni klienci promocji świątecznej 2025 mają osobną ofertę odnowienia, którą możemy sprawdzić.' },
    { q: 'Czy mogę zachować telefon i numer?', a: 'Zwykle tak. Przynieś zgodny, odblokowany telefon, numer konta i PIN do przeniesienia od obecnego operatora. Nie wyłączaj usługi do zakończenia transferu.' },
    { q: 'Czy 25GB ze stałą ceną oznacza brak kolejnych opłat?', a: 'Nie. Nadal płacisz za wybrany okres planu. Promocyjna stawka trwa, dopóki konto jest aktywne i spełnia warunki. Zmiana planu lub odłączenie mogą zakończyć rabat.' },
    { q: 'Czy mogę łączyć promocje?', a: 'Promocji świątecznej i planu 25GB nie można łączyć z innymi ofertami dla klientów. Oferta rodzinna i odnowienia mają osobne warunki. Potwierdzimy odpowiednią opcję przed aktywacją.' },
    { q: 'Jak zgłosić telefon do naprawy?', a: 'Wybierz Zgłoś naprawę, wskaż model, problem i preferowaną godzinę przyjęcia. Potwierdzimy cenę, części i termin. Dożywotnia gwarancja jest dostępna na wybrane naprawy; szczegóły są na paragonie.' }
  ],
  seo: { homeTitle: 'Naprawa telefonów Chicago i Ultra Mobile | CellzTech', homeDescription: 'Naprawa iPhone i Samsung w Chicago. Październikowe oferty Ultra Mobile, telefony bez blokady i lokalna pomoc w Cellz Repairz, 3412 N Harlem Ave.', ultraTitle: 'Ultra Mobile Chicago: oferty październikowe | CellzTech', ultraDescription: 'Plany Ultra od $102 z góry za 12 miesięcy, oferty 25GB i 4 linie za $100. Aktywacja i pomoc z przeniesieniem numeru w Chicago.' }
};

const es: typeof en = {
  ui: { october: 'OCTUBRE 2026 · CHICAGO', book: 'Solicitar reparación', call: 'Llamar a la tienda', compare: 'Ver ofertas de Ultra', details: 'Ver detalles', ask: 'Consultar este plan', choose: 'Elige tus datos', perMonth: '/mes', equivalent: 'equivalente mensual', upfront: 'pagados por adelantado', tax: 'Impuestos y cargos adicionales.', newCustomer: 'Solo clientes nuevos', allPlans: 'Comparar los 5 planes', plan: 'Datos mensuales', total: 'Primeros 12 meses', standard: 'Renovación anual estándar', months: 'meses', month: 'mes', selected: 'Seleccionado', back: 'Volver a los planes', terms: 'Requisitos y detalles importantes', offerEnds: 'Activa antes del 31 de diciembre de 2026.', expired: 'Esta oferta terminó. Consulta los planes actuales.', check: 'Consultar elegibilidad', faq: 'Preguntas que vale la pena hacer.', home: 'Inicio', directions: 'Cómo llegar', learn: 'Más información', included: 'Incluido en los planes elegibles', priceNote: 'Solo el plan. Teléfono vendido por separado.', noPayment: 'No cobramos en línea. Confirmamos la elegibilidad y el precio final antes de activar.' },
  home: { eyebrow: 'TU TIENDA LOCAL DE TELÉFONOS Y SERVICIO MÓVIL', title: 'Reparación de teléfonos en Chicago.', accent: 'Mejor conectados.', intro: 'Una pantalla rota. Una batería que dura poco. Una factura demasiado alta. CellzTech te ayuda con reparaciones de iPhone, Samsung y tabletas, planes Ultra Mobile y teléfonos disponibles localmente.', artLabel: 'Un mejor plan para tu teléfono.', artNote: 'Conserva tu teléfono compatible desbloqueado y tu número.', offerTag: 'OFERTA ULTRA MOBILE DE OCTUBRE', offerSmall: 'Plan de 8GB · primeros 12 meses · clientes nuevos', repairTitle: 'Tu teléfono de cada día. La ayuda que necesitas.', repairIntro: 'Cuéntanos qué falla. Revisamos el dispositivo, explicamos las opciones y confirmamos piezas, precio y tiempo antes de reparar.', localTitle: 'Ayuda de verdad. Aquí en Harlem.', localText: 'Visita Cellz Repairz para reparaciones, transferencias de número, configuración y preguntas de tecnología. Todo en una tienda local.', shopTitle: 'Más opciones para seguir conectado.', shopText: 'Explora teléfonos usados y desbloqueados, cargadores, fundas y protección de pantalla. Consulta las existencias y la ayuda de configuración.', phones: 'Ver teléfonos', accessories: 'Ver accesorios', offersTitle: 'Ahorros de octubre. Condiciones claras.', offersIntro: 'Tres formas distintas de ahorrar. Compara el pago inicial, la duración y quién califica.', trust: ['Garantía de por vida en reparaciones selectas', 'Ayuda gratuita para activar Ultra', 'Conserva tu número', 'Asistencia local en tienda'] },
  repairs: { names: ['Cambio de pantalla', 'Cambio de batería', 'Problemas de carga', 'Cristal trasero', 'Cámara y sonido', '¿No sabes qué falla?'], descriptions: ['Grietas, líneas o fallas táctiles.', 'Una batería que se agota rápido.', 'Puerto flojo o un teléfono que no carga.', 'Opciones para el cristal trasero dañado.', 'Problemas de cámara, altavoz y micrófono.', 'Empieza con una revisión del dispositivo.'], warranty: 'La garantía depende de la reparación y la pieza elegida. Tu recibo indica la cobertura exacta. La garantía por defectos no cubre daños físicos.', link: 'Ver todos los servicios', process: ['Indica tu dispositivo y el problema', 'Confirmamos opciones y tiempo', 'Trae el dispositivo a la tienda'], note: 'La hora solicitada no es una cita confirmada hasta que te contactemos.' },
  brief: { holiday: 'Un año completo. Mitad del precio.', holidayBody: '50% de descuento en planes de 12 meses elegibles. Desde $102 por adelantado con 8GB mensuales.', monthly: '25GB. Un precio para conservar.', monthlyBody: '$29 en el plan de un mes. Equivalentes mensuales más bajos al prepagar varios meses.', family: 'Cuatro líneas. Una factura menor.', familyBody: '4 líneas Ultra Unlimited por $100 al mes en total. Se requiere una nueva cuarta línea elegible.' },
  holiday: { badge: 'OFERTA DE TEMPORADA · 50% DE DESCUENTO', title: 'Un año completo con Ultra.', accent: 'Mitad del precio del plan.', intro: 'Elige un plan de 12 meses elegible y paga una sola vez por el primer año. Te ayudamos a revisar el teléfono, conservar tu número y activar en tienda.', subtitle: 'Cinco planes. Precios claros.', description: 'Cada precio corresponde a los 12 meses pagados por adelantado. La cifra mensual es un equivalente, no un pago mensual.', after: 'Después del año introductorio, la renovación es al precio estándar.', eligibility: 'Para clientes nuevos cuyo número y dispositivo no hayan estado activos con Ultra en los últimos 90 días. Activa y paga el plan dentro del período promocional. Excluye el plan promocional de 25GB. No se combina con otras ofertas para clientes.', features: ['Datos 5G / 4G LTE', 'Llamadas nacionales y textos globales ilimitados', 'Llamadas ilimitadas a más de 90 destinos', 'Llamadas y textos en México y Canadá', 'Hotspot y llamadas por Wi-Fi', 'En la red T-Mobile'], network: 'Planes Unlimited: después de 35GB/mes, los usuarios pueden notar menor velocidad cuando la red está ocupada. Video en SD. Hotspot: hasta 10GB en Unlimited y 25GB en Unlimited+.', original: 'Precio estándar', discounted: 'Total promocional', heroNote: 'Elige un plan para ver el pago inicial exacto.' },
  monthly: { badge: '25GB DE POR VIDA', title: '¿Prefieres conservar tu precio?', intro: 'Conserva el precio promocional de 25GB mientras permanezcas activo en el plan elegible. Elige la duración al activar.', duration: 'Elige el período de pago', help: 'Más meses prepagados significan un equivalente mensual menor.', rule: 'Solo clientes nuevos; el número y el dispositivo no deben haber estado activos con Ultra en los últimos 90 días. Debes mantener el plan elegible. Cambiar de plan, desconectarlo o no renovar puede terminar el descuento. Elige la duración al activar: no se permite cambiar después entre duraciones promocionales.', auto: 'El plan de un mes de $29 también ofrece $3 de descuento al inscribirte y pagar con Auto-Renew: $26 más impuestos.', separate: 'Es una oferta distinta; no recibe el 50% adicional de la promoción de temporada.', features: ['25GB de datos rápidos cada mes', 'Llamadas nacionales y textos globales ilimitados', 'Llamadas a más de 90 destinos', 'Hotspot y llamadas por Wi-Fi'] },
  family: { badge: 'PLAN FAMILIAR ULTRA', title: 'Conecta a tu familia. Conserva el ahorro.', intro: 'Cuatro líneas Ultra Unlimited por $100 al mes en total, con funciones internacionales y ayuda de activación local.', totalLabel: 'total por 4 líneas / mes', lineLabels: ['Primera línea', 'Segunda línea', 'Tercera línea', 'Nueva cuarta línea'], eligibility: 'Para cuentas nuevas y clientes actuales elegibles que agreguen una nueva cuarta línea Add-A-Line antes del 31 de diciembre de 2026. El precio continúa mientras las líneas requeridas sigan activas en el plan elegible. Las tabletas pueden formar parte de las cuatro líneas.', features: ['4 líneas Unlimited', 'Hasta 10GB de hotspot por línea', 'Llamadas internacionales incluidas', 'Requiere una nueva cuarta línea'], compare: 'Compara el total familiar', lineCount: 'Número de líneas', priceFor: 'Precio mensual total del plan', terms: 'Impuestos y cargos adicionales. Después de 35GB/mes puede reducirse la velocidad con congestión; video SD.' },
  renewal: { badge: '¿YA TIENES ULTRA?', title: 'Una renovación especial para clientes elegibles de la promoción 2025.', intro: 'Algunos clientes que se unieron con Ultra Holiday 2025 pueden obtener 33% de descuento en una renovación de 12 meses elegible, equivalente a cuatro meses gratis.', rule: 'La elegibilidad depende de la cuenta. Ultra avisa por texto, correo o aplicación. Debes estar activo; los clientes con Auto-Renew no califican. Excluye 25GB y Add-A-Line. Disponible hasta el 31 de enero de 2027. Revisamos contigo el crédito y el total final.', total: 'Renovación elegible de 12 meses', cta: 'Consultar mi renovación' },
  roam: { services: "Llamadas. Textos. Datos. Tu número.", badge: 'GO ROAM WORLD PASS', title: '¿Viajas? Lleva tu número contigo.', body: 'Pregunta por Go Roam World Pass para llamadas, textos y datos en el extranjero. Ultra anuncia opciones por menos de $1 al día con cualquier plan.', note: 'Disponibilidad, velocidad y cobertura varían por destino. El pase se compra por separado. Confirma país, precio y límites antes de viajar.', cta: 'Consultar mi destino', detail: 'Ver información de roaming Ultra' },
  transfer: { badge: 'CAMBIAR ES MÁS FÁCIL', title: 'Nuevo plan. Mismo número.', intro: 'Te ayudamos en tienda a revisar la compatibilidad y transferir tu número.', steps: ['Trae un teléfono compatible desbloqueado', 'Consigue tu número de cuenta actual', 'Pide el PIN de transferencia al operador', 'Mantén tu línea actual activa'], warning: 'No canceles el servicio anterior antes de completar la transferencia.', cta: 'Recibir ayuda para cambiar' },
  contact: { title: 'Encontremos el siguiente paso.', intro: 'Repara tu teléfono, compara un plan o consulta las existencias. Habla con CellzTech en Chicago.', hours: 'Lun.–vie. 11 AM–7 PM · Sáb. 11 AM–3 PM · Domingo cerrado', address: '3412 N Harlem Ave, STE A · Chicago, IL 60634', independent: 'CellzTech es operado por Cellz Repairz LLC. Servicio de reparación independiente; no autorizado por Apple. Teléfono ilustrativo; no se incluye un teléfono con el plan móvil.' },
  faq: [
    { q: '¿$8.50 es un pago mensual?', a: 'No. La oferta de 8GB cuesta $102 por adelantado por los primeros 12 meses, equivalente a $8.50 al mes. Impuestos y cargos adicionales. La renovación es al precio estándar.' },
    { q: '¿Los clientes actuales reciben 50% de descuento?', a: 'La oferta de 50% es para clientes nuevos. El número y el dispositivo no deben haber estado activos con Ultra en los últimos 90 días. Los clientes elegibles de la promoción 2025 tienen una oferta de renovación separada.' },
    { q: '¿Puedo conservar mi teléfono y mi número?', a: 'Normalmente sí. Trae un teléfono compatible desbloqueado, el número de cuenta y el PIN de transferencia de tu operador. Mantén el servicio activo hasta terminar la transferencia.' },
    { q: '¿25GB de por vida significa que no vuelvo a pagar?', a: 'No. Sigues pagando por la duración elegida. La tarifa promocional continúa mientras permanezcas activo y elegible en ese plan. Cambiar de plan o desconectarlo puede terminar el descuento.' },
    { q: '¿Puedo combinar las ofertas?', a: 'Las promociones de temporada y de 25GB no se combinan con otras ofertas. Los planes familiares y de renovación tienen sus propios requisitos. Confirmaremos la opción correcta antes de activar.' },
    { q: '¿Cómo solicito una reparación?', a: 'Usa Solicitar reparación para indicar el dispositivo, problema y hora preferida. Te contactamos para confirmar precio, piezas y tiempo. Hay garantía de por vida en reparaciones selectas; la cobertura exacta está en el recibo.' }
  ],
  seo: { homeTitle: 'Reparación de teléfonos Chicago y Ultra | CellzTech', homeDescription: 'Reparación de iPhone y Samsung en Chicago. Ofertas Ultra Mobile de octubre, teléfonos desbloqueados y ayuda local en Cellz Repairz, 3412 N Harlem Ave.', ultraTitle: 'Ultra Mobile Chicago: ofertas de octubre | CellzTech', ultraDescription: 'Planes Ultra desde $102 por 12 meses prepagados, planes de 25GB y 4 líneas por $100. Activación y transferencia de número en Chicago.' }
};

const uk: typeof en = {
  ui: { october: 'ЖОВТЕНЬ 2026 · ЧИКАГО', book: 'Подати заявку на ремонт', call: 'Зателефонувати', compare: 'Пропозиції Ultra', details: 'Умови пропозиції', ask: 'Запитати про план', choose: 'Виберіть обсяг даних', perMonth: '/міс.', equivalent: 'місячний еквівалент', upfront: 'оплата наперед', tax: 'Податки та збори додатково.', newCustomer: 'Лише для нових клієнтів', allPlans: 'Порівняти 5 планів', plan: 'Дані щомісяця', total: 'Перші 12 місяців', standard: 'Стандартне річне поновлення', months: 'місяців', month: 'місяць', selected: 'Вибрано', back: 'До планів', terms: 'Умови та важлива інформація', offerEnds: 'Активуйте до 31 грудня 2026 року.', expired: 'Пропозиція завершилася. Запитайте про актуальні плани.', check: 'Перевірити право на знижку', faq: 'Відповіді на важливі запитання.', home: 'Головна', directions: 'Прокласти маршрут', learn: 'Докладніше', included: 'У відповідних планах', priceNote: 'Ціна лише за план. Телефон продається окремо.', noPayment: 'Оплата онлайн не стягується. Перед активацією підтверджуємо умови та остаточну ціну.' },
  home: { eyebrow: 'ВАШ МІСЦЕВИЙ МАГАЗИН І СЕРВІС ТЕЛЕФОНІВ', title: 'Ремонт телефонів у Чикаго.', accent: 'Кращий зв’язок.', intro: 'Тріснув екран? Швидко сідає батарея? Завеликий рахунок за зв’язок? CellzTech допомагає з ремонтом iPhone, Samsung і планшетів, планами Ultra Mobile та купівлею телефону в магазині.', artLabel: 'Кращий план для вашого телефону.', artNote: 'Збережіть сумісний розблокований телефон і свій номер.', offerTag: 'ЖОВТНЕВА ПРОПОЗИЦІЯ ULTRA MOBILE', offerSmall: 'План 8GB · перші 12 місяців · нові клієнти', repairTitle: 'Телефон, на який ви покладаєтесь. Допомога, яка потрібна.', repairIntro: 'Розкажіть про несправність. Ми перевіримо пристрій, пояснимо варіанти й підтвердимо запчастини, ціну та терміни перед ремонтом.', localTitle: 'Справжня допомога. Тут, на Harlem.', localText: 'Завітайте до Cellz Repairz для ремонту, перенесення номера, налаштування пристрою та порад щодо техніки. Усе в одному місцевому магазині.', shopTitle: 'Більше для вашого телефону.', shopText: 'Перегляньте вживані та розблоковані телефони, зарядні пристрої, чохли й захист екрана. Запитайте про наявність і допомогу з налаштуванням.', phones: 'Переглянути телефони', accessories: 'Переглянути аксесуари', offersTitle: 'Жовтневі знижки. Зрозумілі умови.', offersIntro: 'Три різні способи заощадити. Порівняйте оплату наперед, тривалість і вимоги.', trust: ['Довічна гарантія на окремі ремонти', 'Безкоштовна допомога з активацією Ultra', 'Збережіть свій номер', 'Місцева підтримка в магазині'] },
  repairs: { names: ['Заміна екрана', 'Заміна батареї', 'Проблеми із заряджанням', 'Ремонт заднього скла', 'Камера та звук', 'Не знаєте, що сталося?'], descriptions: ['Тріщини, смуги або проблеми із сенсором.', 'Батарея, що швидко розряджається.', 'Нестабільний порт або відсутність заряджання.', 'Варіанти ремонту пошкодженого заднього скла.', 'Несправності камери, динаміка й мікрофона.', 'Почніть з огляду пристрою.'], warranty: 'Гарантія залежить від ремонту та вибраної запчастини. Точні умови зазначені в чеку. Гарантія на дефекти не покриває фізичні пошкодження.', link: 'Усі послуги ремонту', process: ['Вкажіть пристрій і проблему', 'Ми підтвердимо варіанти й терміни', 'Принесіть пристрій до магазину'], note: 'Бажаний час приймання не є підтвердженим записом, доки ми з вами не зв’яжемося.' },
  brief: { holiday: 'Цілий рік. Половина ціни плану.', holidayBody: '50% знижки на відповідні річні плани. Від $102 наперед за 8GB щомісяця.', monthly: '25GB. Ціна надовго.', monthlyBody: '$29 за одномісячний план. Нижчий місячний еквівалент за передоплати кількох місяців.', family: 'Чотири лінії. Менший рахунок.', familyBody: '4 лінії Ultra Unlimited за $100 на місяць разом. Потрібна нова четверта лінія, що відповідає умовам.' },
  holiday: { badge: 'СВЯТКОВА ПРОПОЗИЦІЯ · ЗНИЖКА 50%', title: 'Цілий рік з Ultra.', accent: 'За половину ціни плану.', intro: 'Виберіть відповідний річний план та сплатіть за перший рік один раз. Допоможемо перевірити телефон, зберегти номер і активувати послугу в магазині.', subtitle: 'П’ять планів. Прозорі ціни.', description: 'Кожна сума нижче — за 12 місяців з оплатою наперед. Менша місячна сума є еквівалентом, а не щомісячним платежем.', after: 'Після першого року поновлення відбувається за стандартною ціною.', eligibility: 'Для нових клієнтів, чий номер і пристрій не були активні в Ultra протягом попередніх 90 днів. Активуйте й оплатіть план у період пропозиції. Акційний план 25GB виключено. Не поєднується з іншими пропозиціями для клієнтів.', features: ['Дані 5G / 4G LTE', 'Необмежені дзвінки в США та глобальні SMS', 'Необмежені дзвінки до понад 90 напрямків', 'Дзвінки та SMS у Мексиці й Канаді', 'Хотспот і дзвінки через Wi-Fi', 'У мережі T-Mobile'], network: 'Плани Unlimited: після 35GB/міс. швидкість може знижуватись за перевантаження мережі. Відео в SD. Хотспот: до 10GB в Unlimited і 25GB в Unlimited+.', original: 'Стандартна ціна', discounted: 'Святкова сума', heroNote: 'Виберіть план, щоб побачити точну передоплату.' },
  monthly: { badge: '25GB ЗІ СТАЛОЮ ЦІНОЮ', title: 'Бажаєте зберегти свою ціну?', intro: 'Зберігайте акційну ціну 25GB, доки залишаєтеся активним користувачем відповідного плану. Тривалість вибирається під час активації.', duration: 'Виберіть період оплати', help: 'Більше місяців наперед — нижчий місячний еквівалент.', rule: 'Лише для нових клієнтів; номер і пристрій не повинні бути активними в Ultra протягом попередніх 90 днів. Акційна ціна залежить від збереження відповідного плану. Зміна плану, відключення або непоновлення можуть завершити знижку. Виберіть тривалість під час активації — пізніше змінити акційний період не можна.', auto: 'Одномісячний план за $29 також має знижку $3 за підключення та оплати через Auto-Renew: $26 плюс податок.', separate: 'Це окрема пропозиція, без додаткової святкової знижки 50%.', features: ['25GB швидкісних даних щомісяця', 'Необмежені дзвінки в США та глобальні SMS', 'Дзвінки до понад 90 напрямків', 'Хотспот і дзвінки через Wi-Fi'] },
  family: { badge: 'СІМЕЙНИЙ ПЛАН ULTRA', title: 'Об’єднайте родину. Збережіть вигоду.', intro: 'Чотири лінії Ultra Unlimited за $100 на місяць разом, з міжнародними функціями та місцевою допомогою з активацією.', totalLabel: 'разом за 4 лінії / місяць', lineLabels: ['Перша лінія', 'Друга лінія', 'Третя лінія', 'Нова четверта лінія'], eligibility: 'Для нових облікових записів і відповідних чинних клієнтів, які додають нову четверту лінію Add-A-Line до 31 грудня 2026 року. Акційна ціна триває, доки потрібні лінії активні на відповідному плані. Планшети можуть входити до чотирьох ліній.', features: ['4 лінії Unlimited', 'До 10GB хотспоту на лінію', 'Міжнародні дзвінки включено', 'Потрібна нова четверта лінія'], compare: 'Порівняйте сімейну суму', lineCount: 'Кількість ліній', priceFor: 'Загальна місячна ціна плану', terms: 'Податки та збори додатково. Після 35GB/міс. можливе зниження швидкості за перевантаження; відео SD.' },
  renewal: { badge: 'ВИ ВЖЕ З ULTRA?', title: 'Поновлення для відповідних клієнтів святкової пропозиції 2025.', intro: 'Деякі клієнти Ultra Holiday 2025 можуть отримати 33% знижки на відповідне річне поновлення — еквівалент чотирьох місяців безкоштовно.', rule: 'Право на пропозицію залежить від облікового запису. Ultra повідомляє SMS, електронною поштою або в застосунку. Потрібний активний статус; клієнти з Auto-Renew не відповідають умовам. Плани 25GB і Add-A-Line виключено. До 31 січня 2027 року. Разом перевіримо кредит на поновлення та остаточну суму.', total: 'Відповідне поновлення на 12 місяців', cta: 'Запитати про поновлення' },
  roam: { services: "Дзвінки. SMS. Інтернет. Ваш номер.", badge: 'GO ROAM WORLD PASS', title: 'Подорожуєте? Візьміть свій номер.', body: 'Запитайте про Go Roam World Pass для дзвінків, SMS і даних за кордоном. Ultra рекламує варіанти менш ніж за $1 на день з будь-яким планом.', note: 'Доступність, швидкість і покриття залежать від країни. Пакет купується окремо. Перед подорожжю перевірте країну, ціну та ліміти.', cta: 'Запитати про країну подорожі', detail: 'Інформація про роумінг Ultra' },
  transfer: { badge: 'ПРОСТЕ ПЕРЕНЕСЕННЯ НОМЕРА', title: 'Новий план. Той самий номер.', intro: 'У магазині допоможемо перевірити сумісність і перенести номер.', steps: ['Принесіть сумісний розблокований телефон', 'Отримайте номер поточного рахунку', 'Отримайте PIN для перенесення в оператора', 'Залиште поточну лінію активною'], warning: 'Не скасовуйте стару послугу до завершення перенесення номера.', cta: 'Допомога з переходом' },
  contact: { title: 'Знайдімо правильний наступний крок.', intro: 'Відремонтуйте телефон, порівняйте план або перевірте наявність. Зверніться до CellzTech у Чикаго.', hours: 'Пн.–пт. 11:00–19:00 · Сб. 11:00–15:00 · Неділя зачинено', address: '3412 N Harlem Ave, STE A · Chicago, IL 60634', independent: 'CellzTech працює під управлінням Cellz Repairz LLC. Незалежний сервіс, не авторизований Apple. Телефон показано для ілюстрації; до мобільного плану він не входить.' },
  faq: [
    { q: 'Чи є $8.50 щомісячним платежем?', a: 'Ні. Святковий план 8GB коштує $102 наперед за перші 12 місяців, тобто $8.50 на місяць в еквіваленті. Податки та збори додатково. Поновлення за стандартною ціною.' },
    { q: 'Чи отримають чинні клієнти Ultra знижку 50%?', a: 'Пропозиція 50% призначена для нових клієнтів. Номер і пристрій не повинні бути активні в Ultra протягом попередніх 90 днів. Для відповідних клієнтів пропозиції 2025 є окрема знижка на поновлення.' },
    { q: 'Чи можу я зберегти телефон і номер?', a: 'Зазвичай так. Принесіть сумісний розблокований телефон, номер рахунку та PIN для перенесення від свого оператора. Залиште послугу активною до завершення перенесення.' },
    { q: 'Чи означає 25GB зі сталою ціною, що більше не треба платити?', a: 'Ні. Ви й далі оплачуєте вибраний період. Акційна ставка триває, доки ви активні та відповідаєте умовам плану. Зміна плану або відключення можуть завершити знижку.' },
    { q: 'Чи можна поєднувати пропозиції?', a: 'Святкова пропозиція та план 25GB не поєднуються з іншими акціями. Сімейні плани та поновлення мають окремі умови. Підтвердимо правильний варіант перед активацією.' },
    { q: 'Як подати заявку на ремонт?', a: 'Виберіть Подати заявку на ремонт, вкажіть пристрій, проблему й бажаний час. Ми зв’яжемося для підтвердження ціни, запчастин і термінів. Довічна гарантія діє на окремі ремонти; точні умови зазначені в чеку.' }
  ],
  seo: { homeTitle: 'Ремонт телефонів у Чикаго та Ultra Mobile | CellzTech', homeDescription: 'Ремонт iPhone і Samsung у Чикаго. Жовтневі пропозиції Ultra Mobile, розблоковані телефони й місцева допомога в Cellz Repairz, 3412 N Harlem Ave.', ultraTitle: 'Ultra Mobile Чикаго: жовтневі пропозиції | CellzTech', ultraDescription: 'Плани Ultra від $102 наперед за 12 місяців, плани 25GB і 4 лінії за $100. Активація та допомога з перенесенням номера в Чикаго.' }
};

export const octoberCopy: Record<OctoberLanguage, typeof en> = { en, pl, es, uk };
export type OctoberCopy = typeof en;